# Generated by Django 5.1.1 on 2025-05-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/images'),
        ),
    ]
